# Generated by Django 5.1 on 2024-08-31 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.FileField(blank=True, default='media/default.png', null=True, upload_to='image_users/'),
        ),
    ]
