# Generated by Django 5.1 on 2024-08-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_user_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='data_publicacao',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='foto',
            field=models.FileField(blank=True, default='image_users/default.png', null=True, upload_to='image_users/'),
        ),
    ]
